apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fe.fullname" . }}
  labels:
    {{- include "fe.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      labels:
        {{- include "fe.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "bglamb/mockapi:latest"
          imagePullPolicy: Always
          env:
          - name: BACKEND1
            value: backend1.default.svc.cluster.local
          - name: BACKEND2
            value: backend2.default.svc.cluster.local
          volumeMounts:
          - mountPath: /operation.txt
            subPath: operation.txt
            name: operation
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      volumes:
      - name: operation
        configMap:
          name: operation          
